DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS title;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE title (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  bought TEXT NOT NULL,
  symbol TEXT NOT NULL,
  amount REAL NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);